// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUmSdDCdKEXQuYJb8NyBbri4k8dNbfIh0',
    appId: '1:115011245163:web:0c395b4639b888d9ae0d2e',
    messagingSenderId: '115011245163',
    projectId: 'insta-flutter-clone-1bf0f',
    authDomain: 'insta-flutter-clone-1bf0f.firebaseapp.com',
    storageBucket: 'insta-flutter-clone-1bf0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbdxC8Duh6SGqk33prSdmtwMbrUYdgHTk',
    appId: '1:115011245163:android:60081d213802a7a5ae0d2e',
    messagingSenderId: '115011245163',
    projectId: 'insta-flutter-clone-1bf0f',
    storageBucket: 'insta-flutter-clone-1bf0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlI5dAJdxHeOYac136u6_AG0RXhx3RsI',
    appId: '1:115011245163:ios:64a98b236f24f5f4ae0d2e',
    messagingSenderId: '115011245163',
    projectId: 'insta-flutter-clone-1bf0f',
    storageBucket: 'insta-flutter-clone-1bf0f.appspot.com',
    iosClientId: '115011245163-kei2s3kar6tvc3t04l9uc174enk86to2.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaFlutterClone',
  );
}
